apiVersion: v1
kind: Service
metadata:
  name: kamailio
  namespace: voip
  labels:
    component: kamailio
spec:
  ports:
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: 5060
  selector:
    component: kamailio

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kamailio
  namespace: voip
  labels:
    component: kamailio
spec:
  selector:
    matchLabels:
      component: kamailio
  template:
    metadata:
      name: kamailio
      labels:
        component: kamailio
    spec:
      hostNetwork: true
      volumes:
        - name: config
      containers:
        - name: kamailio
          image: yongs2/kamailio:1.0.1
          env:
            - name: CLOUD
              value: private
          volumeMounts:
            - name: config
              mountPath: /data/kamailio
        - name: rtpproxy
          image: yongs2/rtpproxy:1.0.1
          env:
            - name: CLOUD
              value: private
        - name: dispatchers
          image: cycoresystems/dispatchers
          command:
            - /app
            - "-set"
            - voip:asterisk=1:5080
          volumeMounts:
            - name: config
              mountPath: /data/kamailio
